@startuml
                skinparam monochrome true
                skinparam classAttributeIconSize 0
                scale 2
namespace app {
	namespace views {
		class Add {
			+methods
			+get()
			+post()
		}
	}
}
@enduml