@startuml

skinparam monochrome true

skinparam classAttributeIconSize 0


class Car {
    -__year_model
    -__make
    -__speed

    -__init__(year_model, make)
    +accelerate()
    +brake(age)
    +get_speed()
    -__str__()
}

@enduml