@startuml

skinparam monochrome true
skinparam classAttributeIconSize 0
scale 2

class UI {
    -ip_edit
    -file_name_edit
    -config_edit
    -vsrx

    -__init__():
    -getConfigClicked():
}

@enduml
