@startuml

skinparam monochrome true
skinparam classAttributeIconSize 0
scale 2

class VSRX {
    -channel
    -cli_active
    -mode
    -client

    -__init__()
    -startCLI()

    +connect()
    +showConfiguration()
    +close()
}

@enduml
